In [88]:
pd.options.display.max_rows = 200

In [102]:
시군구명='남구'

df=pd.read_csv('전처리완료dataset/전체/화재_(서울제외).csv')
# df.drop('Unnamed: 0',axis=1,inplace=True)

df1= df.loc[df.loc[:,'시군구명'].str.contains(시군구명,na=False)]

df1

      시도명 시군구명 읍/면/동  설치유무  화재발생횟수
79  광주광역시   남구   양림동     0       5
80  광주광역시   남구  방림1동     0       0
81  광주광역시   남구  방림2동     0       0
82  광주광역시   남구  봉선1동     0       0
83  광주광역시   남구  봉선2동     0       0
84  광주광역시   남구    사동     1       0
85  광주광역시   남구   월산동     0       0
86  광주광역시   남구  월산4동     0       0
87  광주광역시   남구  월산5동     0       0
88  광주광역시   남구  백운1동     0       0
89  광주광역시   남구  백운2동     0       0
90  광주광역시   남구  주월1동     0       0
91  광주광역시   남구  주월2동     0       0
92  광주광역시   남구   효덕동     0       0
93  광주광역시   남구   송암동     0       0
94  광주광역시   남구   대촌동     0       0

In [101]:
df=pd.read_csv('전처리완료dataset/전체/화재_(서울제외).csv')
df

         �õ��� �ñ�����     ��/��/��  ��ġ����  ȭ��߻�Ƚ��
0       ������  ������      �ֹ�����        1         0
1       ������  ������        �����        0        19
2       ������  ������         �ջ��        0         0
3       ������  ������       ������        0         8
4       ������  ������       ������        1        25
5       ������  ������        �����        0         0
6       ������  ������        ��õ��        0        19
7       ������  ������        �����        0         0
8       ������  ������        ȫ����        0         0
9       ������  ������         �߾ӵ�        0         0
10      ������  ������        ��õ��        0         0
11      ������  ������        ��1��        0         0
12      ������  ������        ��2��        0         0
13      ������  ������      ����1��        0         0
14      ������  ������      ����2��        0         0
15      ������  ������          �ʴ絿        0         0
16      ������  ������       ������        0         3
17      ������  ������         ���        0        13
18      ������  ������       ������        0         0
19      ������  ������       ������        0         0
20      ������  ������       ������        0         0
21      ������  ������       ������        1        19
22      ������  ������         ����        1         8
23      ������  ������          �ϸ�        1        15
24      ������  ������         �⸰��        1        14
25      ������  ������        ��ȭ��        1        11
26      ������  ������          �󳲸�        1        11
27      ������   ��õ��        �ź���        1        33
28      ������   ��õ��         ����        1        17
29      ������   ��õ��        �����        1        11
30      ������   ��õ��        �ŵ���        1         7
31      ������   ��õ��         ����        0         7
32      ������   ��õ��         ����        1        20
33      ������   ��õ��         ��ϸ�        1         9
34      ������   ��õ��         �ϻ��        0         7
35      ������   ��õ��       ������        1        24
36      ������   ��õ��        �����        0        18
37      ������   ��õ��         ����        1         3
38      ������   ��õ��         ���        0         0
39      ������   ��õ��       ������        0         0
40      ������   ��õ��        ��ȭ��        1         6
41      ������   ��õ��          �Ҿ絿        0         0
42      ������   ��õ��      ����1��        0         0
43      ������   ��õ��      ����2��        0         0
44      ������   ��õ��      ����3��        0         0
45      ������   ��õ��       ȿ��1��        0         0
46      ������   ��õ��       ȿ��2��        0         0
47      ������   ��õ��       ȿ��3��        0         0
48      ������   ��õ��         ���絿        1        16
49      ������   ��õ��          ��赿        1         0
50      ������   ��õ��       ������        0         0
51      ������   ��õ��         �Ż�쵿        0         0
52         ��⵵    ����       ������        1        45
53         ��⵵    ����        ���Ǹ�        1        27
54         ��⵵    ����  û���(�ܼ���)        0         0
55         ��⵵    ����          ���        1        23
56         ��⵵    ����       ������        1         9
57         ��⵵    ����          �ϸ�        1        23
58   ���ֱ�����    ���걸      ����1��        0         0
59   ���ֱ�����    ���걸      ����2��        0         0
60   ���ֱ�����    ���걸         ���굿        1         8
61   ���ֱ�����    ���걸         ���ﵿ        0         0
62   ���ֱ�����    ���걸          ��浿        0         0
63   ���ֱ�����    ���걸          ��굿        1         0
64   ���ֱ�����    ���걸      ����1��        0         0
65   ���ֱ�����    ���걸      ����2��        0         0
66   ���ֱ�����    ���걸         ��Ƶ�        1         6
67   ���ֱ�����    ���걸       ÷��1��        0         0
68   ���ֱ�����    ���걸       ÷��2��        0         0
69   ���ֱ�����    ���걸        �Ű���        1         0
70   ���ֱ�����    ���걸         ���        1         0
71   ���ֱ�����    ���걸        ��â��        1         0
72   ���ֱ�����    ���걸        ���ϵ�        0         0
73   ���ֱ�����    ���걸        �ϳ���        0         0
74   ���ֱ�����    ���걸          �Ӱ        0         0
75   ���ֱ�����    ���걸         ���        0         0
76   ���ֱ�����    ���걸           ��        0         0
77   ���ֱ�����    ���걸         �ﵵ��        0         1
78   ���ֱ�����    ���걸       ������        0         0
79   ���ֱ�����    ����         �縲��        0         5
80   ���ֱ�����    ����        �渲1��        0         0
81   ���ֱ�����    ����        �渲2��        0         0
82   ���ֱ�����    ����      ����1��        0         0
83   ���ֱ�����    ����      ����2��        0         0
84   ���ֱ�����    ����           �絿        1         0
85   ���ֱ�����    ����         ���굿        0         0
86   ���ֱ�����    ����      ����4��        0         0
87   ���ֱ�����    ����      ����5��        0         0
88   ���ֱ�����    ����       ���1��        0         0
89   ���ֱ�����    ����       ���2��        0         0
90   ���ֱ�����    ����       �ֿ�1��        0         0
91   ���ֱ�����    ����       �ֿ�2��        0         0
92   ���ֱ�����    ����        ȿ����        0         0
93   ���ֱ�����    ����         �۾ϵ�        0         0
94   ���ֱ�����    ����        ���̵�        0         0
95     �λ걤����    ����    ����ŵ�1��        1         0
96     �λ걤����    ����    ����ŵ�2��        1         4
97     �λ걤����    ����    ����ŵ�3��        1         7
98     �λ걤����    ����    ����ŵ�1��        1         1
99     �λ걤����    ����    ����ŵ�3��        1        13
100    �λ걤����    ����    ����ŵ�4��        0         0
101    �λ걤����    ����         �ιε�        0         0
102    �λ걤����    ����         �ƹ̵�        0         0
103    �λ걤����    ����         ���嵿        1         3
104    �λ걤����    ����         �湫��        0         0
105    �λ걤����    ����     ���ι�1��        0         0
106    �λ걤����    ����     ���ι�2��        0         0
107    �λ걤����    ����        �ϳ���        1        17
108      ���󳲵�    �žȱ�       ������        1        12
109      ���󳲵�    �žȱ�       ������        1        16
110      ���󳲵�    �žȱ�       ������        0         1
111      ���󳲵�    �žȱ�        ���ڸ�        0         6
112      ���󳲵�    �žȱ�       ������        0         4
113      ���󳲵�    �žȱ�         ��ݸ�        0         1
114      ���󳲵�    �žȱ�        ���ʸ�        1         4
115      ���󳲵�    �žȱ�         ����        0         3
116      ���󳲵�    �žȱ�        ���Ǹ�        0         6
117      ���󳲵�    �žȱ�        ���Ǹ�        0         1
118      ���󳲵�    �žȱ�         ����        0         2
119      ���󳲵�    �žȱ�        ���¸�        0         7
120      ���󳲵�    �žȱ�         �ȱݸ�        0         1
121      ���󳲵�    �žȱ�        ���¸�        1         2
122     ����ϵ�   ��â��        ��â��        1        24
123     ����ϵ�   ��â��       ������        1         9
124     ����ϵ�   ��â��         �ƻ��        1        10
125     ����ϵ�   ��â��        �����        1        13
126     ����ϵ�   ��â��       ������        1         8
127     ����ϵ�   ��â��        ���ϸ�        1         9
128     ����ϵ�   ��â��        �ظ���        1         8
129     ����ϵ�   ��â��        ���۸�        1         8
130     ����ϵ�   ��â��         ����        0        12
131     ����ϵ�   ��â��        �ɿ���        1         4
132     ����ϵ�   ��â��        �����        1        13
133     ����ϵ�   ��â��       ������        1         7
134     ����ϵ�   ��â��        �Ÿ���        1         4
135     ����ϵ�   ��â��         �ξȸ�        1        11
136     ����ϵ�   ���ֱ�       ������        1         9
137     ����ϵ�   ���ֱ�        ��ǳ��        1         2
138     ����ϵ�   ���ֱ�        ��õ��        1         7
139     ����ϵ�   ���ֱ�        �����        1         9
140     ����ϵ�   ���ֱ�        �ȼ���        1         8
141     ����ϵ�   ���ֱ�        �γ���        1         3
142     ����ϵ�  ������     ��������        0        11
143     ����ϵ�  ������          �ϸ�        0        10
144     ����ϵ�  ������         �Ծϸ�        0         0
145     ����ϵ�  ������        �Ҽ���        0         8
146     ����ϵ�  ������        ���θ�        0        12
147     ����ϵ�  ������       ������        0         0
148     ����ϵ�  ������        ��õ��        0         5
149     ����ϵ�  ������        �����        0         0
150     ����ϵ�  ������        �����        0         0
151     ����ϵ�  ������        ���θ�        0         0
152     ����ϵ�  ������        �����        0        12
153     ����ϵ�  ������        �˵���        0         0
154     ����ϵ�  ������        ĥ����        0         0
155     ����ϵ�  ������         �곻��        0         4
156     ����ϵ�  ������         ��ܸ�        0         3
157     ����ϵ�  ������       ������        0         8
158     ����ϵ�  ������        �����        0         0
159     ����ϵ�  ������        �����        0         0
160     ����ϵ�  ������          �ñ⵿        0         6
161     ����ϵ�  ������          �ʻ굿        0         0
162     ����ϵ�  ������       ������        0         5
163     ����ϵ�  ������         ��ҵ�        0         3
164     ����ϵ�  ������          �󱳵�        0         0
165    ��û����    �ƻ��        ��ġ��        0        10
166    ��û����    �ƻ��        �����        0        35
167    ��û����    �ƻ��         �۾Ǹ�        1         9
168    ��û����    �ƻ��       ������        0         0
169    ��û����    �ƻ��       ������        1         0
170    ��û����    �ƻ��       ������        1        28
171    ��û����    �ƻ��        ���θ�        1        26
172    ��û����    �ƻ��        ���ָ�        1         0
173    ��û����    �ƻ��        �����        1         8
174    ��û����    �ƻ��       ������        1        12
175    ��û����    �ƻ��        ��â��        0        28
176    ��û����    �ƻ��       �¾�1��        0         0
177    ��û����    �ƻ��       �¾�2��        0         0
178    ��û����    �ƻ��       �¾�3��        0         0
179    ��û����    �ƻ��       �¾�4��        0         0
180    ��û����    �ƻ��       �¾�5��        0         0
181    ��û����    �ƻ��       �¾�6��        0         0
182     ��û�ϵ�   ��õ��        ��õ��        1        31
183     ��û�ϵ�   ��õ��        �����        0        25
184     ��û�ϵ�   ��õ��        �����        1        17
185     ��û�ϵ�   ��õ��        �����        1        16
186     ��û�ϵ�   ��õ��         ����        1         7
187     ��û�ϵ�   ��õ��        �̿���        0        19
188     ��û�ϵ�   ��õ��     ��������        1        11

In [ ]:
화재데이터(2,강남구,대치동) = 인구데이터(서울특별시,강남구,대치1동,24922,대치2동,대치3동) 
동만 화재 데이터랑 똑같이 바꿔줘

In [ ]:
def dong(x):
    import re

    p = re.compile('[가-힣]\S*[0-9]{1}[읍면동가]')

    r = p.findall(x)
    
    return ''.join(r)

In [ ]:

시도명 = '서울특별시'
시군구명 = '성동구' 
제공기관명 = f'{시도명} {시군구명}'

df= pd.read_csv('dataset/서울_어린이보호구역_주소O.csv')
# df = df.rename(columns=df.iloc[0])
df.drop('Unnamed: 0',axis=1,inplace=True)
df1 = df.loc[df.loc[:,'제공기관명'].str.contains(제공기관명,na=False)]
df1.head(1)

In [ ]:
x

시도명= 제공기관명.split()[0]
시군구명= 제공기관명.split()[1]
detail_1['시도명']= 시도명
detail_1['시군구명']= 시군구명
get_col = ['시도명','시군구명','읍/면/동']
detail_1 = detail_1[get_col]
detail_1['어린이보호구역총계'] = 1
grouped = detail_1.groupby('읍/면/동')[['어린이보호구역총계']].sum()
result = grouped.reset_index()
result['시도명'] = '서울특별시'
result['시군구명'] = '노원구'
result = result[['시도명','시군구명','읍/면/동','어린이보호구역총계']]
result

In [ ]:
# pd.read_csv('전처리완료dataset/human/서울특별시.csv')

In [69]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

import re
def dong(x):
    import re

    p = re.compile('[가-힣]\S*[0-9]{1}[가동][0-9]?[가동]?')

    r = p.findall(x)
    
    return ''.join(r)


# [가-힣]\S*[0-9]{1}[읍면동가][0-9]?[읍면동가]?

In [70]:

# u1 = ['공릉동', '상계동', '월계동', '중계동', '하계동']
시도명 = '서울특별시'
시군구명 = '성동구' 
# 제공기관명 = f'{시도명} {시군구명}'
# u1 = '검색하실 읍/면/동'

In [71]:
df= pd.read_csv('전처리완료dataset/human/서울특별시.csv')
# df = df.rename(columns=df.iloc[0])
# df.drop('Unnamed: 0',axis=1,inplace=True)
df = df.loc[df.loc[:,'시군구명'].str.contains(시군구명,na=False)]
df

      시도명 시군구명    읍/면/동  등록인구수
52  서울특별시  성동구    왕십리2동  17416
53  서울특별시  성동구      마장동  23459
54  서울특별시  성동구      사근동  13512
55  서울특별시  성동구     행당1동  14363
56  서울특별시  성동구     행당2동  24151
57  서울특별시  성동구      응봉동  15824
58  서울특별시  성동구    금호1가동  15795
59  서울특별시  성동구    금호4가동  14842
60  서울특별시  성동구   성수1가1동  16851
61  서울특별시  성동구   성수1가2동  13738
62  서울특별시  성동구   성수2가1동  17146
63  서울특별시  성동구   성수2가3동  11457
64  서울특별시  성동구      송정동  11143
65  서울특별시  성동구      용답동  12724
66  서울특별시  성동구   왕십리도선동  27588
67  서울특별시  성동구  금호2.3가동  23584
68  서울특별시  성동구      옥수동  26912

In [72]:
dff= df.copy()
# # dff['읍/면/동'] = detail_1['읍/면/동'].apply(lambda x : dong(x))

In [73]:
def simple_dong(x):
    import re
    
    a = re.split(r'[0-9]', x)
    b= a[0]
    
    return b

In [74]:
# df.loc[:,'읍/면/동'].str.contains('동')



# df['읍/면/동'][

In [75]:
dff['읍/면/동'] = dff['읍/면/동'].apply(lambda x : simple_dong(x))

dff

# import re
# for i in dff['읍/면/동']:
#     if (dff.loc[:,'읍/면/동'].str.contains('동'))==True:
#         i = re.split(r'[동]', i)[0]


# dff

      시도명 시군구명   읍/면/동  등록인구수
52  서울특별시  성동구     왕십리  17416
53  서울특별시  성동구     마장동  23459
54  서울특별시  성동구     사근동  13512
55  서울특별시  성동구      행당  14363
56  서울특별시  성동구      행당  24151
57  서울특별시  성동구     응봉동  15824
58  서울특별시  성동구      금호  15795
59  서울특별시  성동구      금호  14842
60  서울특별시  성동구      성수  16851
61  서울특별시  성동구      성수  13738
62  서울특별시  성동구      성수  17146
63  서울특별시  성동구      성수  11457
64  서울특별시  성동구     송정동  11143
65  서울특별시  성동구     용답동  12724
66  서울특별시  성동구  왕십리도선동  27588
67  서울특별시  성동구      금호  23584
68  서울특별시  성동구     옥수동  26912

In [16]:

dff= 제공기관명.split(" ")[0]
시군구명= 제공기관명.split(" ")[1]
detail_1['시도명']= 시도명
detail_1['시군구명']= 시군구명
get_col = ['시도명','시군구명','읍/면/동']
detail_1 = detail_1[get_col]
detail_1['어린이보호구역총계'] = 1
grouped = detail_1.groupby('읍/면/동')[['어린이보호구역총계']].sum()
result = grouped.reset_index()
result['시도명'] = '서울특별시'
result['시군구명'] = '노원구'
result = result[['시도명','시군구명','읍/면/동','어린이보호구역총계']]
result

     시도명 시군구명  읍/면/동  어린이보호구역총계
0  서울특별시  노원구                34
1  서울특별시  노원구  금호동1가          3
2  서울특별시  노원구  금호동2가          2
3  서울특별시  노원구  금호동3가          1
4  서울특별시  노원구  금호동4가          4
5  서울특별시  노원구  성수동1가          4
6  서울특별시  노원구  성수동2가          3

In [ ]:
# result.to_csv(f'전처리완료dataset/어린이/{시도명}{시군구명}어린이보호.csv',index=0)
# result = pd.read_csv(f'전처리완료dataset/어린이/{시도명}{시군구명}어린이보호.csv')
# result

In [84]:
df= pd.read_csv('전처리완료dataset/human/강원도.csv')
df

     시도명 시군구명 읍/면/동  등록인구수
0    강원도  춘천시   신북읍   8080
1    강원도  춘천시    동면  20120
2    강원도  춘천시   동산면   1560
3    강원도  춘천시   신동면   2594
4    강원도  춘천시    남면   1123
..   ...  ...   ...    ...
183  강원도  양양군    서면   3017
184  강원도  양양군   손양면   2485
185  강원도  양양군   현북면   2648
186  강원도  양양군   현남면   3135
187  강원도  양양군   강현면   4423

[188 rows x 4 columns]

In [81]:
df = df.loc[df.loc[:,'시군구명'].str.contains('서대문구',na=False)]
df

       시도명  시군구명 읍/면/동  등록인구수
188  서울특별시  서대문구   천연동  18049
189  서울특별시  서대문구   홍제동  54921
190  서울특별시  서대문구   홍은동  51000
191  서울특별시  서대문구  남가좌동  47137
192  서울특별시  서대문구  북가좌동  51504
193  서울특별시  서대문구   충현동  21229
194  서울특별시  서대문구  북아현동  16956
195  서울특별시  서대문구   신촌동  23051
196  서울특별시  서대문구   연희동  39105

In [3]:
import pandas as pd
df=pd.read_csv('dataset/경찰청_전국 경찰서별 강력범죄 발생 현황_20191231.csv',encoding='cp949')
df

     발생년도     경찰서     소계  살인  강도     절도     폭력
0    2018   서울중부서  2,239   1   5  1,057  1,176
1    2018   서울종로서  1,881   5   1    744  1,131
2    2018  서울남대문서  1,584   1   6    798    779
3    2018  서울서대문서  2,596   5   3  1,062  1,526
4    2018   서울혜화서  1,573   1   2    739    831
..    ...     ...    ...  ..  ..    ...    ...
505  2019   경남함안서    305   1   0    107    197
506  2019   경남의령서    161   0   2     34    125
507  2019  제주서귀포서  2,199   4   7    897  1,291
508  2019   제주동부서  3,135  11   3  1,173  1,948
509  2019   제주서부서  3,030   5  11  1,144  1,870

[510 rows x 7 columns]

In [4]:
import pandas as pd
df=pd.read_excel('dataset/전국어린이보호구역표준데이터-20210801.xls')
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,시설종류,대상시설명,소재지도로명주소,소재지지번주소,위도,경도,관리기관명,관할경찰서명,CCTV설치여부,CCTV설치대수,보호구역도로폭,데이터기준일자,제공기관코드,제공기관명
1,초등학교,오덕초등학교,강원도 철원군 동송읍 오덕로159,강원도 철원군 동송읍 오덕리 산23,38.2229984579,127.232171,강원도 철원군,철원경찰서,Y,1,6,2020-08-26,4300000,강원도 철원군
2,초등학교,문혜초등학교,강원도 철원군 갈말읍 태봉로1556,강원도 철원군 갈말읍 문혜리 1099-4,38.1868442263,127.3180714284,강원도 철원군,철원경찰서,Y,1,6,2020-08-26,4300000,강원도 철원군
3,어린이집,로이스어린이집,대구광역시 달서구 진천로3길 85-11,대구광역시 달서구 진천동 470-23,35.80974735,128.5214745,대구광역시 달서구청,대구광역시 달서경찰서,Y,1,6,2021-03-15,3470000,대구광역시 달서구
4,어린이집,예원어린이집,대구광역시 달서구 월곡로47안길 33-7,대구광역시 달서구 상인동 588,35.8149995,128.5403876,대구광역시 달서구청,대구광역시 달서경찰서,Y,1,6,2021-03-15,3470000,대구광역시 달서구

In [5]:
import pandas as pd
df=pd.read_csv('dataset/전국어린이보호구역표준데이터.csv',encoding='cp949')
df.head()

,시설종류,대상시설명,소재지도로명주소,소재지지번주소,위도,경도,관리기관명,관할경찰서명,CCTV설치여부,CCTV설치대수,보호구역도로폭,데이터기준일자,제공기관코드,제공기관명
0,초등학교,오덕초등학교,강원도 철원군 동송읍 오덕로159,강원도 철원군 동송읍 오덕리 산23,38.222998,127.232171,강원도 철원군,철원경찰서,Y,1.0,6,2020-08-26,4300000,강원도 철원군
1,초등학교,문혜초등학교,강원도 철원군 갈말읍 태봉로1556,강원도 철원군 갈말읍 문혜리 1099-4,38.186844,127.318071,강원도 철원군,철원경찰서,Y,1.0,6,2020-08-26,4300000,강원도 철원군
2,어린이집,로이스어린이집,대구광역시 달서구 진천로3길 85-11,대구광역시 달서구 진천동 470-23,35.809747,128.521475,대구광역시 달서구청,대구광역시 달서경찰서,Y,1.0,6,2021-03-15,3470000,대구광역시 달서구
3,어린이집,예원어린이집,대구광역시 달서구 월곡로47안길 33-7,대구광역시 달서구 상인동 588,35.814999,128.540388,대구광역시 달서구청,대구광역시 달서경찰서,Y,1.0,6,2021-03-15,3470000,대구광역시 달서구
4,어린이집,해뜰어린이집,대구광역시 달서구 월곡로47안길 33-4,대구광역시 달서구 상인동 588,35.814793,128.540309,대구광역시 달서구청,대구광역시 달서경찰서,Y,1.0,6,2021-03-15,3470000,대구광역시 달서구

In [2]:
import pandas as pd
import numpy as np

In [4]:


df= pd.read_csv('전처리완료dataset/전체/u1기준데이터인구밀도전국통합본.csv')
df.시도명.unique()

array(['서울특별시', '강원도', '광주광역시', '경기도', '부산광역시', '전라남도', '전라북도', '충청남도',
       '충청북도'], dtype=object)

In [2]:
import pandas as pd
import numpy as np

In [37]:
df=pd.read_excel('dataset/전국스마트가로등표준데이터-20210801.xls')
df= df[[]]

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
스마트가로등유형,시도명,시군구명,도로명,소재지도로명주소,소재지지번주소,위도,경도,스마트가로등형태,점등상태여부,센서종류,...,위급상황신고가능여부,앱서비스명,앱서비스제공내용,기타서비스,설치연도,관리기관명,관리기관전화번호,데이터기준일자,제공기관코드,제공기관명
1,충청남도,홍성군,남부순환로,NaN,충청남도 홍성군 홍성읍 옥암리 872-2,36.599743,126.663126,01,Y,없음,...,N,NaN,NaN,NaN,NaN,홍성군,041-630-1582,2020-07-07,4600000,충청남도 홍성군
1,충청남도,홍성군,남부순환로,NaN,충청남도 홍성군 홍성읍 옥암리 872-2,36.599327,126.662999,01,Y,없음,...,N,NaN,NaN,NaN,NaN,홍성군,041-630-1582,2020-07-07,4600000,충청남도 홍성군
1,충청남도,홍성군,남부순환로,NaN,충청남도 홍성군 홍성읍 옥암리 872-2,36.598884,126.662850,01,Y,없음,...,N,NaN,NaN,NaN,NaN,홍성군,041-630-1582,2020-07-07,4600000,충청남도 홍성군
1,충청남도,홍성군,남부순환로,NaN,충청남도 홍성군 홍성읍 옥암리 872-2,36.594208,126.668597,01,Y,없음,...,N,NaN,NaN,NaN,NaN,홍성군,041-630-1582,2020-07-07,4600000,충청남도 홍성군
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,광주광역시,남구,진다리로6번길,광주광역시 남구 진다리로 6번길 6 (해피니스 원룸 옆),NaN,35.13654029,126.9020821,01,Y,없음,...,Y,NaN,NaN,NaN,2015,광주광역시 남구청,062-607-3832,2020-09-25,3610000,광주광역시 남구
2,광주광역시,남구,천변좌로338번길,광주광역시 남구 천변좌로 338번길 7 (빛고을시민문화관 앞 광주공원 버스정류장),NaN,35.14790588,126.9078967,01,Y,없음,...,Y,NaN,NaN,NaN,2015,광주광역시 남구청,062-607-3832,2020-09-25,3610000,광주광역시 남구
2,광주광역시,남구,천변좌로,광주광역시 남구 천변좌로 368 (서현동물병원앞),NaN,35.1457889,126.9120791,01,Y,없음,...,Y,NaN,NaN,NaN,2015,광주광역시 남구청,062-607-3832,2020-09-25,3610000,광주광역시 남구
2,광주광역시,남구,천변좌로,광주광역시 남구 천변좌로 370 (서현동물병원 앞),NaN,35.14565736,126.9121576,01,Y,없음,...,Y,NaN,NaN,NaN,2015,광주광역시 남구청,062-607-3832,2020-09-25,3610000,광주광역시 남구
2,광주광역시,남구,천변좌로,광주광역시 남구 천변좌로 380 (최재훈웨딩 맞은편),NaN,35.14485836,126.9127347,01,Y,없음,...,Y,NaN,NaN,NaN,2015,광주광역시 남구청,062-607-3832,2020-09-25,3610000,광주광역시 남구

In [18]:
import pandas as pd
df= pd.read_csv('dataset/국토교통부_전국 법정동_20201119.csv',encoding='cp949')
len(df.iloc[:,3].unique())

5685

In [39]:
df1= pd.read_csv('dataset/행정동_법정동.csv',error_bad_lines=False,encoding='cp949')

len(df1.iloc[:,3].unique())

18697

In [49]:
df1= pd.read_csv('dataset/행정동.csv',error_bad_lines=False,encoding='cp949')

len(df1.iloc[:,1].unique())

b'Skipping line 824: expected 2 fields, saw 3\nSkipping line 826: expected 2 fields, saw 3\nSkipping line 834: expected 2 fields, saw 3\n'

3674